# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeb634a66feade271fd8c08ff0d72379e69894d24b09dfde298feeecd13d8a64cf1ac991b73f8d61f77c82774d3f3fabc0f9d4cccf88fb96f33be13b09cd806a

test:
  secret_key_base: dd6eddad80c07069bac58904c69e6a6418ca8f0604f0c5760352a5de681a90d87cea2fdbad9c58b98ff640327987514097d99c648f46350b1971f94c7b9e2d57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
